name: Deploy to VPS

on:
  push:
    branches:
      - main # Cambia a 'master' si tu rama principal se llama así

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            cd ${{ secrets.PROJECT_PATH }}
            git pull origin main
            
            # Actualizar el módulo de Odoo por consola (opcional)
            # docker compose exec -T odoo odoo -d ute_sostenible -u ute_sostenible --stop-after-init --no-http
            
            docker compose restart odoo
